spring:
  application:
    name: InstaMate
  profiles:
    active: prod
server:
  port: 8080
  
# 로컬 환경  
---
spring:
  config:
    activate: 
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://instamate.jp:3306/teriwoo321?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul&autoReconnect=true
    username: teriwoo321
    password: ghksrka9274!
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      idleTimeout: 600000  # 추가: 유휴 상태에서 연결 유지 시간
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: -1
upload.path: src/main/resources/static/administration/upload
      
# 배포 환경
--- 
spring:
  config:
    activate: 
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/teriwoo321?useUnicode=true&characterEncoding=utf8
    username: teriwoo321
    password: ghksrka9274!
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: -1
upload.path: /home/hosting_users/teriwoo321/tomcat/webapps/upload